#!/bin/sh

echo Starting riemann_syslog with development console..

exec erl -pa $PWD/ebin\
         -pa $PWD/apps/*/ebin\
         -pa $PWD/deps/*/ebin\
         -pa $PWD/dev/*/ebin\
         -config `dirname $0`/dev.config\
         -args_file `dirname $0`/start.args
